(setq modulepath (concat (file-name-directory load-file-name) "rlmodule.so"))
(module-load modulepath)

(setq x 100.0)
(setq y 100.0)
(setq vx 200.0)
(setq vy 200.0)
(setq cw 100.0)
(setq ch 100.0)
(setq g 1000.0)

(rl/init-window 800 600 "Bouncing square")
(rl/set-target-fps 144)
(while (not (rl/window-should-close))
    (rl/begin-drawing)
        (rl/clear-background '(24 24 24 255))
        (setq dt (rl/get-frame-time))
        (setq w (rl/get-screen-width))
        (setq h (rl/get-screen-height))

        (setq vy (+ vy (* g dt)))

        (setq nx (+ x (* vx dt)))
        (setq ny (+ y (* vy dt)))
        
        (if (or (< nx 0) (> (+ nx cw) w))
            (setq vx (- 0 vx))
            (setq x nx)
        )
        (if (or (< ny 0) (> (+ ny ch) h))
            (setq vy (- 0 vy))
            (setq y ny)
        )
        
        (rl/draw-rectangle-v `(,x ,y) `(,cw ,ch) '(255 255 255 255))
        (rl/draw-fps 0 0)
    (rl/end-drawing)
)
(rl/close-window)